#!/usr/bin/env python3
"""
Lists all databases in a MongoDB server.
"""

from pymongo import MongoClient


def list_all_databases():
    """
    Connects to the local MongoDB server and prints all database names.
    """
    client = MongoClient()
    databases = client.list_database_names()
    for db in databases:
        print(db)


if __name__ == "__main__":
    list_all_databases()
